### ISSUE TITLE
query params are not recognized any more

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [azagniotov/stubby4j#10]
``` yaml
-  request:
      method: POST
      url: test-url
      query:
         param: 1
      headers:
         content-type: application/json
      file: body.txt
   response:
      status: 200
      headers:
         content-type: application/json
      body: '"true"'
```

will result in next stub (result of toString() of stubHttpLifecycles):

```
[StubHttpLifecycle{request=StubRequest{url='test-url', method='POST', post='null', file='{
  "field" : "val"
}', headers={content-type=application/json}}, response=StubResponse{status='200', body='"true"', latency='null', headers={content-type=application/json}, params={}}}]
```

as you can see there is nothing  that corresponds to param: 1

UPDATE: ok, now I see that you have removed 'query' field from text of description here https://github.com/azagniotov/stubby4j/blob/master/docs/YAML.md but it is still in examples. Please fix examples.
