### ISSUE TITLE
How to make dynamic xml request

### ISSUE THREAD

**Issue by golfapipol** [azagniotov/stubby4j#102]
I have a problem when I want to stub SOAP api with regexp (.*) in dynamic field but it's not work
```
      -  request:
            method: POST
            url: /Service.svc
            query: 
            wsdl: 
            file: request.xml

      response:
            status: 200
            headers:
            content-type: application/xml
            file: response.xml
```
here is request.xml
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:tem="http://tempuri.org/">
  <soapenv:Header/>
  <soapenv:Body>
    <tem:Action>
      <tem:PolicyDate>(.*)</tem:PolicyDate>
      <tem:ExpireDate>(.*)</tem:ExpireDate>
    </tem:PlanInquiry>
  </soapenv:Body>
</soapenv:Envelope>
```
sample post json
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
  <soapenv:Header/>
  <soapenv:Body>
    <tem:Action>
      <tem:PolicyDate>10/10/2018</tem:PolicyDate>
      <tem:ExpireDate>12/12/2018</tem:ExpireDate>
    </tem:PlanInquiry>
  </soapenv:Body>
</soapenv:Envelope>
```
