### ISSUE TITLE
Problem with line separator in WIN/UNIX

### ISSUE THREAD

**Issue by moleksyuk** [azagniotov/stubby4j#11]
Steps to reproduce on **Windows**:
1.Create file for body request (post-body-as-file.json):

```
{
    "name": "value",
    "param": "description"
}
```

2.Define request/response:

```
-  request:
      method: POST
      url: /some/uri
      headers:
         content-type: application/json
      file: ../data/post-body-as-file.json

   response:
      headers:
         content-type: application/json
      status: 200
      body: OK
```

3.Try to post configured request on **UNIX**.

Expected: Get success response.
Actual: 
- Windows: works perfect
- Unix: No data found for request... etc. (No match)

Problem is related to parsing line separator in post-body-as-file.json. On Unix file reader continues using WIN line separator and post body from java code using UNIX line separator which causes mismatching in posted request and configured.
