### ISSUE TITLE
Use dynamically generated identifier in the response

### ISSUE THREAD

**Issue by azagniotov** [azagniotov/stubby4j#14]
Use regex matching groups to determine which back-references are available for insertion into the response body.

This would match things like `/root/resource_name` with `resource_name` as the captured backreference `$1`:

``` yaml
-  request:
      url: /^\/root\/([a-zA-Z_]+)$/
   response:
      body: You've just hit the <% $1 %> application route!
```

As for the response body, you could use `.erb` syntax, like fakerest, to insert backreferences

This would require modifying the overwritten class `equals` function for `StubRequest`, and the function (forget the name) that uses `StubResponse.body` to set the response and make it use erb interpolation using the backreferences captured from the url.

For more context: https://github.com/azagniotov/stubby4j/issues/12
