### ISSUE TITLE
Split yaml config file

### ISSUE THREAD

**Issue by harrysun2006** [azagniotov/stubby4j#145]
Hey Alexander,
My team starts to use stubby4j. It's a lightweight mocking tool and we love its simplicity. Thank you for bringing up this wonderful tool.
However, while we keep adding stub endpoints into the yaml config file, it becomes bigger and bigger. I've done some research around, but couldn't find a feature like "import" or "include" to allow us to split the all-in-one yaml config file into a few smaller yaml files.
I'm wondering is there a plan for such features in the future development?
Thanks,
Harry

**Comment by azagniotov** [comment]
Hi @harrysun2006 ,

Thank you for the kind words!

You are right - there is one main YAML config file. But, there is an option to use the `file` key under `request` or/and `response` sections in order to "include" large stubbed request payloads or response bodies. I wonder if the following can make your lives easier: https://github.com/azagniotov/stubby4j#file  

Please let me know if the above helped.

Cheers,
Alex

**Comment by harrysun2006** [comment]
Hi Alex,

Thanks for your prompt response. Actually, we have split request and response payloads in separate folders and files on per service/endpoint basis. So the stubby component in our project has a structure like:
- stubby.yaml
```
request:
  url: /api/service1/endpoint1
response:
  status: 200
  file: service1/response1.json
... ...
request:
  url: /api/service1/endpoint2
response:
  status: 200
  file: service1/response2.json

request:
  url: /api/service2/endpoint1
response:
  status: 200
  file: service2/response1.json
```
and correspondingly, we have service1, service2 folders and response1.json, response2.json in service1 folder etc. etc.

Our application talks with many downstream services, and the `stubby.yaml` becomes bloated. If we have something like below in the main `stubby.yaml` file:
```
includes:
  - service1.yaml
  - service2.yaml
  - ... ...
  - servicen.yaml
```
and then each `service.yaml` sub config file define the stubs for each service, that will make the code more organised.

I'm keen to know your thoughts about it.

Cheers,
Harry
