### ISSUE TITLE
How to disable the RegEx pattern cache?

### ISSUE THREAD

**Issue by harrysun2006** [azagniotov/stubby4j#170]
Hey Alex,

I'm just wondering is there a way to disable the RegEx pattern cache from command line? In my project, I need to response different payloads based on the request payload (url and headers are same). So I defined a few rules (request/response) with different RegEx pattern in `post` field and I noticed that the matching is tried on rules in natural order before any such rules are cached. However, after one rule is cached, the matching will be tried on potential matched rules first, this cause some inconsistency issue.
For example, I defined four rules below (pseudo code):
```
- description: rule1
   request:
      method: PUT
      url: service_endpoint
      post: regex1
   response:
      file: response1.json

- description: rule2
   request:
      method: PUT
      url: service_endpoint
      post: regex2
   response:
      file: response2.json

- description: rule3
   request:
      method: PUT
      url: service_endpoint
      post: regex3
   response:
      file: response3.json
```

And then I make a few requests with different payload (matching to the regular expressions). If the payload in first request only matches to rule3, then regex3 will be cached. And in a following request, when the payload matches to both rule1 and rule3, I was expecting rule1 gets matched and response1.json is picked. 

It would be great if there is a way to turn off such RegEx pattern cache. Please let me know your thoughts on it.

Thanks,
Harry
