### ISSUE TITLE
[QUESTION] Regex with XML in request.file and response.file

### ISSUE THREAD

**Issue by itsjxck** [azagniotov/stubby4j#399]
We're using Stubby4J to mock a SOAP API but we're having issues extracting values from the request and injecting them into the response.

The stub config is similar to the following (removed project specific naming):
```
- request:
    method: POST
    url: /path/SomeService
    file: ./requests/ExpectedRequestFormat.xml
 
  response:
    status: 200
    headers:
      content-type: application/xml
    file: ./data/SomeServiceResponse.xml
```

In `ExpectedRequestFormat.xml` we have multiple instances of the following:
```
<ns:SomeElement>${xmlunit.matchesRegex(.*)}</ns:SomeElement>
```

And in `SomeServiceResponse.xml` we have:
```
<ns:SomeOtherElement><% file.1 %></ns:SomeOtherElement>
```

We have also tried the following:
```
<ns:SomeOtherElement><% post.1 %></ns:SomeOtherElement>
<ns:SomeOtherElement><% request.file.1 %></ns:SomeOtherElement>
<ns:SomeOtherElement><% request.post.1 %></ns:SomeOtherElement>
```

However the response is always the raw XML file with no injection of values.

Any ideas what we are doing wrong?
