### ISSUE TITLE
Parameters order should not matter for stubby

### ISSUE THREAD

**Issue by OleksandrBerezianskyi** [azagniotov/stubby4j#4]
Right now URLs should match exactly to trigger stubby response. But URL

```
http://localhost:8882/example?param1=val1&param2=val2
```

is the same (with very rare exceptions) as URL

```
http://localhost:8882/example?param2=val2&param1=val1
```

It would be nice to introduce 'parameters' field to URL field, e.g:

```
- request:
   method: GET
   url: http://localhost:8882/example
    parameters: 
     param1: val1
     param2: val2
  response:
   status: 200
```
