### ISSUE TITLE
OAuth Support for Stubby4j

### ISSUE THREAD

**Issue by nitinpadalia** [azagniotov/stubby4j#42]
Hi,
Would you be able to add oAuth support for Header verification? or may be you could provide us code pointers so that we might change it and sent it to you for review.
-Nitin

**Comment by azagniotov** [comment]
oAuth would be nice to have. Start having a look at YamlParser class which parses that YAML file

**Comment by azagniotov** [comment]
v3.0.2 now supports stubbing authorization header for Bearer token verification, ie: "Authorization: Bearer jgHfjgJKhtkjghklhlkjhllj==". Please refer to doc

**Comment by azagniotov** [comment]
```yaml
-  request:
      url: ^/path/to/bearer$
      method: GET
      headers:
         authorization-bearer: "YTM0NZomIzI2OTsmIzM0NTueYQ=="

   response:
      headers:
         Content-Type: application/json
      status: 200
      body: Your request with Bearer was successfully authorized!
```
