### ISSUE TITLE
Dynamic token replacement not working on body post with JSON content type

### ISSUE THREAD

**Issue by AntoineBro** [azagniotov/stubby4j#47]
the regexp does not match the stub if Content-Type is  application/json  ( probably the same with xml ) 

yaml : 
```yaml
-  request:
      method: [POST]
      url: /client
      post: ".*\\{\"code\":\"(.*)\",\"name.*"
   response:
      status: 201
      header:
          Content-Type: application/json
      body: >
           {"id":"<% post.1 %>","link":"http://mysite.com/client/<% post.1 %>"}
```

body of the response when submitting a POST request with Content-Type=application/json  : 
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /client. Reason:
<pre>    (404) Nothing found for POST request at URI /client
	With post data: {"code":"4f3117dc68","name":"Test site"}
	With headers: {accept=*/*, cache-control=no-cache, connection=keep-alive, user-agent=Apache-HttpClient/4.3.6 (java 1.5), host=localhost:8882, accept-encoding=gzip,deflate, content-length=40, content-type=application/json}</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

result submitting a POST request without Content-type  : 
```
{"id":"4f3117dc68","link":"http://mysite.com/client/4f3117dc68"}

```

This is probably due to https://github.com/azagniotov/stubby4j/commit/69ede0b36b360d37bb892321da7a539ff105c555#diff-15eaafe111640649eb49b61698b0cb2dR251
