### ISSUE TITLE
[BUG] stubb4j testcontainer failing with "exec /bin/sh: exec format error"

### ISSUE THREAD

**Issue by oemergenc** [azagniotov/stubby4j#511]
**Describe the bug**
Hi,
 
I am trying to use this docker image **azagniotov/stubby4j:latest-jre21** with testcontainers to write integration tests. On my development machine (MAC M1) everything runs fine.
When I try to execute my test in a Github runner, the stubb4j based testcontainer fails to start.
See the log output of this run here:
https://github.com/oemergenc/spring-cloud-gateway-upgrade/actions/runs/8092179967/job/22112459714#step:4:1336

**Please provide some basic information about you environment**
- What is your OS: Windows/Mac/*Nix: MAC M1
- What is stubby4j version you are running: I am using this docker image azagniotov/stubby4j:latest-jre21
- Are you running stubby4j in Docker container or as a standalone JAR: Docker container
- If Docker container, what is the image tag: azagniotov/stubby4j:latest-jre21

**YAML config**
```
- web-socket:
    description: this is a web-socket config
    url: /demo/web-socket/1

    on-open:
      policy: once
      message-type: text
      body: successfully_connected
      delay: 200

    on-message:
      - client-request:
          message-type: text
          body: hello_request
        server-response:
          policy: once
          message-type: text
          body: hello_response
          delay: 250

      - client-request:
          message-type: text
          body: disconnect_request
        server-response:
          policy: disconnect
          message-type: text
          body: disconnect_response
          delay: 250
```

**Expected behavior**
The stubb4j testcontainer should start succesfully.

**Additional context**
-
