### ISSUE TITLE
Does it support regular expression in Json post request?

### ISSUE THREAD

**Issue by poramate-to** [azagniotov/stubby4j#54]
I would like to match some regular expressions in the json post request. Is it possible?

```
-   request:
        url: ^/MyServer/services/rest/doclist/
        method: POST
        headers:
                content-type: application/json
        post: '{"userId":"19","requestId":"(.*)","transactionDate":"(.*)","transactionTime":"(.*)"}'

```
