### ISSUE TITLE
Negative JSON Regex

### ISSUE THREAD

**Issue by kieranbop** [azagniotov/stubby4j#62]
When I try and specify negative look ahead regex's within my JSON post I never get the expected response. e.g. 

`- request:
      method: [POST]
      headers:
         content-type: application/json
      url: ^/test
      post: '{"title":"(.*)","firstName":"(^(?!john$).*)"}'
  response:
  - status: 200`

returns a 404 on any call. Although I have tested the above regex + several other variations and no luck. Is there something glaring obvious I am missing?

POST request used:

curl -v -X POST -H "content-type: application/json" -d '{"title":"Ms","firstName":"Jeff"}' http://192.168.10.101:8882/test

**Comment by azagniotov** [comment]
Hi... Thank you for reporting. Could you provide your exact POST request so I can replicate your scenario? Also, just for sanity check: does your regex work outside of stubby?

**Comment by azagniotov** [comment]
I think you are missing an asterisk `*` in the first set of parenthesis, not sure if you also need an asterisk in the second set of parenthesis, i.e.: `(^(?!john$).*)`. Try with the following stubbed  request-response:
```
- request:
      method: [POST]
      headers:
         content-type: application/json
      url: ^/test
      post: >
         {"title":"(.*)","firstName":"(^(?!john$).)"}

   response:
      status: 200
```

**Comment by kieranbop** [comment]
I have updated the original comment with the POST request being used. Yes I have tested that regex + other permutations outside of stubby and that returns me my desired result. Is there a particular regex tester you recommend? 
I can't match your answer above... are you able to provide your POST request also?

**Comment by azagniotov** [comment]
Regarding a regex tester, I would write a simple unit test by trying to compile a regex `Pattern` for the sake of testing the regex, that's basically what stubby uses under the hood - `Pattern` object. That said, perhaps you already done just that, I am not sure :) If you do not want to write junit unit tests, I would Google for Java regex tester online. Can I ask you what regex tester you used to test the regex and permutations?

I will have a more thorough look at this tomorrow. Maybe there is a bug lurking somewhere... Again - thanks for reporting this

**Comment by azagniotov** [comment]
I have created the following JUnit test that compiles a `Pattern` and tweaked the regex a little bit. I am not sure what exactly are your use cases, but maybe the following can help you. Let me know what you think:

https://gist.github.com/azagniotov/fdca8377dac606a0399178940a015825

```
post: >
   {"title":"(.*)","firstName":"((?!john).*)"}
```

**Comment by kieranbop** [comment]
Hello azagniotov, thanks for the fast reply. I have tested above locally and it has started giving me the desired results. My use cases are a couple of JSON requests that are triggered by a particular field (e.g. first name) if one matches then return some sort of 400 response. Similarly with the next response, return back a 200 if the first name doesnt match one specified in the above response.

```yaml
- request:
      method: [POST]
      headers:
         content-type: application/json
      url: ^/test
      post: '{"title":"(.*)","firstName":"(john|dave)"}'
  response:
  - status: 400
  - body: Failed Request

- request:
      method: [POST]
      headers:
         content-type: application/json
      url: ^/test
      post: '{"title":"(.*)","firstName":"((?!john|dave).*)"}'
  response:
  - status: 200
  - body: Passed Request
```

I am happy to close the issue but I'm just wondering whether there are certain limitations on the starting characters in the regex.. e.g ^ start of line etc
