### ISSUE TITLE
getting 500 error with basic setup

### ISSUE THREAD

**Issue by spicecoder** [azagniotov/stubby4j#78]
Hello, stubby4j looks like exactly what I wanted ; however I am getting this {"code":"500","message"="Problem handling request in Admin handler: java.lang.NumberFormatException: For input string: "hello-world""}

when I tried --
the yaml :
-  request:
      method: GET
      url: /hello-world
 
   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World!
 

On the console log :[18:03:20] -> GET [/hello-world]
[18:03:20] <- 500 [/hello-world] Server Error  .  Could you please give me a quick direction ! thanks pronab

**Comment by azagniotov** [comment]
I need to see your YAML exactly as you formatted it... 
Judging by what you have here, your YAML is not formatted correctly.

Make sure that you have something like that:
```
-  request:
      url: /hello-world
      method: GET

   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello
```

**Comment by spicecoder** [comment]
Thanks..shall try tonight..shall get back

**Comment by spicecoder** [comment]
Sorry no luck ; I am attaching the yaml file. Appreciate your help.
online validation says valid yaml.

Thanks
Pronab



Pronab Pal

 Compute the World With Words,Lets Mend It Now.

Join The Community
https://plus.google.com/u/0/communities/111254712011749369781

**Comment by azagniotov** [comment]
I do not see any attachment here. I am not sure if whatever you attach via email will appear in Github

**Comment by spicecoder** [comment]
[hello.txt](https://github.com/azagniotov/stubby4j/files/1377729/hello.txt)
I renamed the file to txt extension as it is not able to take a yaml file attachment. Thanks Pronab

**Comment by azagniotov** [comment]
Hello. I am not sure what's going on at your end, but I start the stubby with the following command:
`java -jar stubby4j-5.0.2-SNAPSHOT.jar --data test.yaml` and can successfully load `http://localhost:8882/hello-world` in the browser in order to get `Hello`

My YAML looks as per what you posted before:
```
-  request:
      url: /hello-world
      method: GET

   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello
```

Are you on Linux, Windows or Mac?

Also, I am going on vacation, so I might be slow to reply.
