### ISSUE TITLE
Stub Identifier

### ISSUE THREAD

**Issue by leonardocaldas** [azagniotov/stubby4j#79]
Add option to configure a name or an ID in each request and be able to update or delete this one using this name or ID.

Example:
```
-  request:
      name: my_action
      method: POST
      url: ^/api/action$

   response:
      status: 200
      headers:
         content-type: application/json
      body: >
        {
          "id": "9136d8b7-f7a7-478d-97a5-53292484aaf6"
        }
```
and then I could update using the specified name
```
PUT /my_action -d '
{
... new stub configuration
}'
```
