### ISSUE TITLE
Tokenized value in the header "Location"

### ISSUE THREAD

**Issue by dimadl** [azagniotov/stubby4j#90]
Hi!
I've faced with the following issue:

Here is an example I'm trying:

```
-  request: 
       method: [GET]
       redirect_uri: ^/v\d/identity/authorize
       query:
          redirect_uri: "https://(.*)/app.*"

   response:
       headers:
         location: https://<% query.redirect_uri.1 %>/auth
       status: 302
```

Unfortunately, doing mentioned request I don't get "location" header in the response at all. Seems like exception happens on backend side. 

Looking into the code, only DefaultResponseHandlingStrategy supports tokenized "location" header.

I can fix it. If you don't mind :)
