### ISSUE TITLE
Fix for Issue#93: Fix not working. Even already working flows stopped working.

### ISSUE THREAD

**Issue by singh-virendra** [azagniotov/stubby4j#95]
I had logged the issue #93 for PATCH method with body support couple of days back. After fix #94 for the same issue, it's not solved, and even already working flows like PUT also stopped working.
Expected: it should return "200" for the flow where the file is not provided in the request, and "404" if the file is configured in the request.
Actual: Always returning response "200" which is configured for the success flow(without any file in the request)
Note: tested for both the request methods:
POST: started failing now, it was working before the fix.
PATCH: provided fix #94 not working. It wasn't working before and it's not working now.

Attached are the logs:
[not_working_logs.txt](https://github.com/azagniotov/stubby4j/files/1912165/not_working_logs.txt)

And the local folder used for manual testing:
[stubby.zip](https://github.com/azagniotov/stubby4j/files/1912167/stubby.zip)

**Comment by azagniotov** [comment]
Thank you for providing this. Could you please provide more information about your use cases:

What request (method, request body, etc) exactly are you sending to the stub server?

**Comment by singh-virendra** [comment]
As mentioned in my previous issue:
I tried to put multiple patch requests in response.yaml, which is not working as expected(as it works for PUT and POST).

**response.yaml**
```
-
  request:
    method: PATCH
    url: /simulator/content/v1/url1
    file: response/service/failure-request.json
  response:
    status: 404

-
  request:
    method: PATCH
    url: /simulator/content/v1/url1
  response:
    status: 200
    headers:
      content-type: application/json
    file: response/service/success.json
```

**failure-request.json**
```
{
  "identifier": {
    "identifierTyp": "IDENTIFIER",
    "identifierVal": "1234567890"
  },
  "permissions": {
    "PERMISSION.PERMISSION1": {
      "value": "ABC"
    }
  },
  "extra": {
    "extraId": "54"
  }
}
```

**success.json**
```
{
  "description": "Queued",
  "transactionId": "123-456-789"
}
```

Expected: It should return the response with 200, if no body is present while making request to url `/simulator/content/v1/url1`, else if the body `failure-request.json` is present then it should return 404 response. 

Actual: it returns the status for which the entry is present first in the file `response.yaml`.

And I have already attached the logs(not_working_logs.txt) response.yaml, failure-request.json, success.json in the zip file (stubby.zip) in this issue's description. 
Please have a look.
