### ISSUE TITLE
Q: using authorization-bearer required "Bearer" to appear twice?

### ISSUE THREAD

**Issue by DvirSh** [azagniotov/stubby4j#98]
I'm using the following yml file:
```yml
- request:
    method: POST
    url: /hello
    headers:
      content-type: 'application/json'
      authorization-bearer: 'testToken'   
  response:
    status: 200
```

And then when using Postman, I'm trying to call the following url:
```http://loclahost:3001/hello```
With headers:
```
Content-Type:application/json
Authorization:Bearer testToken
```

And I get 401.
When using the following headers:
```
Content-Type:application/json
Authorization:Bearer Bearer testToken
```
It works and I get 200.
The thing is, I don't want to specify Bearer twice (and I don't need to).
Is this an issue, or am I doing something wrong?
