### ISSUE TITLE
Error when extracting POST body: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by mhcastro** [azagniotov/stubby4j#99]
**Stubby4j parameters**

VERSION - **4.0.3**
RUNTIME CLASSPATH - **/stubby4j/stubby4j-4.0.3.jar**
LOCAL BUILT DATE - **Wed Oct 26 13:35:23 PDT 2016**

--

Test is to post a physical file. Therefore, given the endpoint:

```
request:
      method: POST
      url: /word/post-test
      headers:
         content-type: application/msword
      file: demo.docx
      body: >
            "Test"
   response:
      status: 200
```
Got the following errors:

`POST [stubs]/word/post-test: Error when extracting POST body: java.util.NoSuchElementException, returning null..`

and

`Failed to match on POST BODY`  ... along with the binary file printed in the command line.

Not sure if this is a bug or not. If not, how to properly test the POST of a physical file using stubby4j?
